# This is a basic workflow to help you get started with Actions

name: Spamhaus DROP lists

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    # branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  schedule:
    - cron: "01 15 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Update Spamhaus drop file
        env:
           CI_COMMIT_AUTHOR: github-actions[bot]
           CI_COMMIT_EMAIL: dlffox@users.noreply.github.com
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $Branch = Get-Date -AsUTC -Format 'yyyyMMddTHHmmssK'

          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        
          git checkout -b $Branch

          $PreDrop = $null
          if (Test-Path drop.txt) {
            $PreDrop = Get-FileHash -Path drop.txt -Algorithm SHA512
          }
          
          ./src/spamhaus-drop-list.ps1 -Path drop.txt

          $PostDrop = Get-FileHash -Path drop.txt -Algorithm SHA512

          Write-Output ('PreDrop : {0}' -f $PreDrop.Hash)
          Write-Output ('PostDrop: {0}' -f $PostDrop.Hash)
          
          if ($PreDrop.Hash -ne $PostDrop.Hash) {
            git add .
            git commit -m ('Updated {0} [skip ci]' -f $Branch)
            git push --set-upstream origin $Branch

            gh pr create --base main --head $Branch --title $Branch --body ('Updated {0}' -f $Branch)
            gh pr merge $Branch --squash --delete-branch
          }
